### ISSUE TITLE
Issue using with nginx reverse proxy

### ISSUE THREAD

**Issue by OpieO1** [axeleroy/self-host-planning-poker#118]
I'm using an nginx reverse proxy (swag) and I can't seem to get this application to work when accessed through the reverse proxy.

There are transport errors displayed in the application and I see the following in the console log.

`Firefox can’t establish a connection to the server at wss://poker.example.com/socket.io/?EIO=4&transport=websocket&sid=CVguRykPVYUwoQT0AC4s. main.js:1:10539`

I've setup a domain (poker.example.com). I've tried two different nginx configs.

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name poker.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

   if ($lan-ip = yes) { set $geo-whitelist yes; }
   if ($geo-whitelist = no) { return 404; }


    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.1.2;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

```

I've also tried redirection with socket.io in the path.

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name poker.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.1.2;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_hide_header X-Frame-Options;
        proxy_redirect off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_hide_header X-Frame-Options;
    }

    location /socket.io/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.1.2;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_hide_header X-Frame-Options;
        proxy_redirect off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
}

```
I used https://socket.io/docs/v3/reverse-proxy/ as an example but it doesn't seem to work as documented.

**Comment by axeleroy** [comment]
Hello,

I'm not familiar with SWAG and from what you've shared there's nothing that seems out of place for me. I personally run [BunkerWeb](https://docs.bunkerweb.io/) which has a [setting to enable WebSocket](https://docs.bunkerweb.io/1.5.1/settings/#reverse-proxy) without any issue.

Have you tried asking for help on LinuxServer's [forum](https://discourse.linuxserver.io/tag/swag) or [Discord](https://discord.gg/YWrKVTn)?

**Comment by OpieO1** [comment]
Thank you for the reply. SWAG has websocket support as well. I had to go back and update my configuration files to their new suggested defaults. I had installed SWAG around June 2022 so my config files had not been updated. This can be closed now.
