### ISSUE TITLE
Duplicate users in a game

### ISSUE THREAD

**Issue by ndrobac-es** [axeleroy/self-host-planning-poker#176]
**Issue description:**
When users join a game, when they press button to save their name, they are able to submit the form multiple times which results in having ghost participants when the game loads up.

**Expected behaviour:**
User should not be able to submit their name multiple times

**Steps to reproduce:**
When you create a new game, open the game URL in incognito window or other browser. When you input name, press multiple times on Join button.

**Potential solution:**
Maybe adding debounce for couple of seconds on Join form to prevent multiple submissions from frontend. Alternatively, add validation on backend side to prevent duplicate users for a single session.

**Comment by axeleroy** [comment]
Hello,

Thank you for your thorough bug report, I quickly developed a fix and I'll make a new point release including the fix.
