### ISSUE TITLE
Language bug

### ISSUE THREAD

**Issue by nrxofficial** [axeleroy/self-host-planning-poker#93]
Hi, I updated my docker container to the latest version. Now the language is bugged out. Is there any bugfix?

![image](https://github.com/axeleroy/self-host-planning-poker/assets/48160610/200dc372-c8a5-46e6-865a-cdb842b892f5)

**Comment by axeleroy** [comment]
Hello,

Thank you for reporting this, I'm going to investigate this issue but my gut feeling is it is a configuration mistake from my part.

**Comment by nrxofficial** [comment]
Thank you!
